### PR TITLE
Added Kinect project with basic hand tracking.

### PR DESCRIPTION
**Pull request by tyalt1**

### CODE REVIEW

**Comment by Steven-ScheffelaarKlots** [comment]
14,000 lines?

**Comment by tyalt1** [comment]
That's all XML for the project setup. Also all the Kinect Unity packages are included in the project. When you clone this you just need the Kinect SDK and then when you open it in Unity it should work.

**Comment by Steven-ScheffelaarKlots** [comment]
OK, I guess that makes things easier

**Comment by Steven-ScheffelaarKlots** [comment]
LGTM

**Pull request merged**
